apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
    nodePort: 30002
  selector:	
    app: guestbook-ui
  type: LoadBalancer
  externalIPs:
  - 127.0.0.0
